# To "make"       run in terminal: "make client" or "make server"
# To "make clean" run in terminal: "make client_clean" or "make server_clean"
kontrolna_tacka:
	make -f makefile.kontrolna_tacka
kontrolna_tacka_clean:
	make clean -f makefile.kontrolna_tacka
