# To "make"       run in terminal: "make client" or "make server"
# To "make clean" run in terminal: "make client_clean" or "make server_clean"
aktuator_zvucnik:
	make -f makefile.aktuator_zvucnik
aktuator_zvucnik_clean:
	make clean -f makefile.aktuator_zvucnik

