# To "make"       run in terminal: "make client" or "make server"
# To "make clean" run in terminal: "make client_clean" or "make server_clean"
senzor_pritiska:
	make -f makefile.senzor_pritiska
senzor_pritiska_clean:
	make clean -f makefile.senzor_pritiska
